### ISSUE TITLE
Where can i get your train dataset?

### ISSUE THREAD

**Issue by ordioma** [biswadeep-roy/Safety-Detection-YOLOv8#1]
Where can i get your train dataset?

**Comment by biswadeep-roy** [comment]
Thank you for your interest in the Safety Detection YOLOv8 project!

The project uses a pre-trained model (ppe.pt), so you do not need to train a dataset from scratch to use it. You can download the pre-trained model from the following link and place it in the project's root directory:

[Download ppe.pt](https://drive.google.com/drive/folders/1Fyr8PdSLKRaVdkP5Xr77hAXIXcObx_Hp?usp=sharing)

If you are interested in training your own model or customizing the detection capabilities, you will need a dataset of images annotated with the objects you want to detect. Here are some steps and resources to get you started:

Collect Data: Gather images relevant to your use case (e.g., images of people wearing different types of PPE).
Annotate Data: Use tools like [LabelImg](https://github.com/tzutalin/labelImg) to label your images with bounding boxes around the objects of interest.
Prepare Dataset: Organize your labeled data in a format compatible with YOLO training (e.g., COCO format or YOLO-specific format).
Train the Model: Follow the YOLOv8 training instructions from the [Ultralytics YOLOv8 repository](https://github.com/ultralytics/yolov8) to train your custom model.
If you need more detailed guidance on any of these steps, feel free to ask!
